-- Crear tabla de transacciones en Supabase
create table transactions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null default auth.uid(),
  type text not null check (type in ('income', 'expense')),
  amount numeric not null check (amount > 0),
  description text not null default '',
  category text not null default 'Otros',
  date timestamptz not null default now(),
  created_at timestamptz not null default now()
);

-- Seguridad: cada usuario solo ve sus datos
alter table transactions enable row level security;

create policy "Users can read own transactions"
  on transactions for select
  using (auth.uid() = user_id);

create policy "Users can insert own transactions"
  on transactions for insert
  with check (auth.uid() = user_id);

create policy "Users can update own transactions"
  on transactions for update
  using (auth.uid() = user_id);

create policy "Users can delete own transactions"
  on transactions for delete
  using (auth.uid() = user_id);

-- Índice para consultas por fecha
create index transactions_user_date_idx on transactions (user_id, date desc);
